export enum ErrorMessage {
	// common form errors
	REQUIRED = 'REQUIRED',
	MIN_LENGTH_4 = 'MIN_LENGTH_4',
	MIN_LENGTH_8 = 'MIN_LENGTH_8',
	MIN_LENGTH_12 = 'MIN_LENGTH_12',
	MAX_LENGTH_255 = 'MAX_LENGTH_255',
	NO_LOWERCASE = 'NO_LOWERCASE',
	NO_UPPERCASE = 'NO_UPPERCASE',
	NO_DIGIT = 'NO_DIGIT',
	NO_SYMBOL = 'NO_SYMBOL',

	// register form erors
	INVALID_EMAIL = 'INVALID_EMAIL',
	PASSWORD_NOT_STRONG_ENOUGH = 'PASSWORD_NOT_STRONG_ENOUGH',
	PASSWORD_NOT_STRONG_ENOUGH_HARD_CHECK = 'PASSWORD_NOT_STRONG_ENOUGH_HARD_CHECK',
	PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH',

	// common errors
	MISSING_FIELDS = 'MISSING_FIELDS',
	INVALID_VALUES = 'INVALID_VALUES',
	UNKNOWN_ERROR = 'UNKNOWN_ERROR',

	// login errors
	INVALID_USERNAME = 'INVALID_USERNAME',
	INVALID_PASSWORD = 'INVALID_PASSWORD',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',

	// register errors
	USERNAME_ALREADY_USED = 'USERNAME_ALREADY_USED',
	EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',

	// session errors
	INVALID_TOKEN = 'INVALID_TOKEN',
	EXPIRED_TOKEN = 'EXPIRED_TOKEN',
	NOT_ACTIVE_TOKEN = 'NOT_ACTIVE_TOKEN',
	TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',

	// change settings errors
	IDENTICAL_PASSWORDS = 'IDENTICAL_PASSWORDS',
}
