const startLorem = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris consectetur tempus elit vitae auctor. Sed luctus euismod augue et dapibus. Aenean cursus libero ac nunc rutrum, sit amet rhoncus ligula ultrices. Praesent convallis tempus volutpat. Maecenas vel velit iaculis, facilisis tellus eu, consequat nibh. Curabitur eleifend turpis vel nulla posuere, vitae viverra nulla condimentum. Sed dapibus nunc risus, a tincidunt ligula sollicitudin rutrum. Cras lacinia purus venenatis, molestie nisi ut, facilisis odio. Nulla facilisi. Cras at maximus mi. Suspendisse quis sapien fringilla, hendrerit sem rhoncus, egestas velit. Etiam iaculis tellus eros, eu elementum ante sagittis interdum.'

const lorem = [
	'Mauris sit amet diam ut elit convallis convallis sit amet sit amet turpis. Ut blandit risus eleifend mauris auctor ultrices. Curabitur nec tortor orci. Duis varius semper lorem et elementum. Nullam sit amet diam id nisi mattis finibus. Proin at feugiat quam. Donec gravida, lectus sit amet fringilla mattis, lectus orci posuere dolor, sed volutpat turpis nulla pretium nulla. Maecenas interdum, lacus ac aliquet mattis, magna enim scelerisque diam, non vestibulum risus felis eget arcu. Suspendisse quis ligula rhoncus, semper metus non, tempor leo. Praesent eget condimentum orci. Fusce sed est in dolor mattis maximus et eu neque. Aliquam eget tristique orci, at scelerisque enim. In nisl urna, varius sit amet elit in, lacinia tempor orci. Nulla nec dolor maximus, egestas velit non, aliquet eros. Donec vehicula felis a tincidunt vehicula. Aliquam velit velit, imperdiet eget euismod ac, tempor eget mauris.',
	'Nulla facilisi. Nulla ullamcorper tellus neque, at finibus odio euismod vehicula. Nunc scelerisque, nisl lacinia eleifend ultricies, risus ligula tristique enim, ut luctus orci dolor varius quam. Aenean bibendum arcu in felis porttitor tristique. Morbi iaculis urna at malesuada vulputate. Praesent sem nibh, vestibulum sit amet dui non, euismod tincidunt massa. Fusce purus leo, auctor eu tortor quis, pretium gravida mi. Fusce ornare massa nisl, a posuere ligula iaculis sed. Donec convallis eros libero, ut vehicula turpis interdum et. Vivamus ultrices, urna id egestas ultrices, est mi malesuada elit, quis hendrerit felis ligula vitae erat.',
	'Donec diam arcu, laoreet eu fermentum non, tincidunt eget urna. Donec tincidunt sem eros, vitae condimentum erat suscipit faucibus. Mauris vulputate pulvinar purus, ac tincidunt dui iaculis nec. Praesent vel est a nisi porta dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ac est nibh. Pellentesque sed libero magna. Proin vestibulum nibh vitae metus eleifend hendrerit. Nam sed dapibus felis, ac facilisis massa.',
	'Fusce sit amet diam odio. Nullam varius tempus eros, et aliquam augue laoreet eu. Duis purus nunc, gravida in elit id, rutrum venenatis turpis. Nulla nec felis ut turpis viverra consequat. Nunc et feugiat velit. Morbi pellentesque elit a orci faucibus imperdiet. Aliquam sit amet purus quis felis mollis tincidunt. Duis id libero non lectus commodo mollis.',
	'Morbi accumsan odio in efficitur ornare. Ut non massa sit amet turpis tempor finibus. Nullam a leo volutpat, iaculis nibh eget, vulputate quam. Suspendisse ac cursus magna. Maecenas ac dolor purus. Sed suscipit orci lorem, eget iaculis purus gravida vel. Curabitur magna massa, interdum ac mattis et, vestibulum at ante. Duis pellentesque dictum faucibus. Sed facilisis lobortis nulla, sit amet tempor sapien. Quisque faucibus turpis in ipsum sollicitudin varius. Vestibulum at nibh semper, aliquam odio eu, pellentesque leo. Mauris eget laoreet metus, eget ullamcorper urna.',
	'Cras pharetra fringilla aliquam. Curabitur eleifend libero dui, nec cursus ipsum porta eu. Nullam maximus imperdiet accumsan. Curabitur fermentum nibh mi, ac vestibulum arcu aliquam vel. Curabitur eget tincidunt ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In egestas finibus erat id hendrerit. Praesent nec erat lorem. Suspendisse ultrices nisi in dolor ornare, vel varius nisi laoreet. Proin at imperdiet magna. Mauris vitae dolor arcu. Sed egestas, neque sit amet malesuada volutpat, enim odio ullamcorper odio, eu eleifend nunc nibh at ex. Ut ac condimentum enim. Nunc bibendum, ipsum ut sagittis consequat, orci sem vestibulum leo, vel sodales sapien nulla ut quam.',
	'Etiam aliquam id sapien vel varius. Mauris eget ipsum neque. Nulla enim odio, maximus a auctor vitae, mattis ac odio. Nunc vehicula nunc vitae lorem finibus, aliquam consequat est ultricies. Curabitur vel placerat elit. Phasellus non turpis eu turpis rhoncus ullamcorper. Sed finibus ligula sit amet nisl mollis sodales. Maecenas aliquet blandit dolor, vitae finibus augue iaculis quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam quis tortor accumsan, iaculis velit maximus, mollis urna. Donec a dapibus arcu, egestas molestie lacus. Suspendisse imperdiet luctus finibus.',
	'Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur non augue eu metus commodo egestas. Donec libero nunc, condimentum vitae eros ut, sollicitudin fermentum lacus. Cras eu accumsan dolor. Cras convallis eros at mollis lacinia. Nulla venenatis dui quis ante egestas vulputate. Sed tellus leo, viverra nec pharetra a, blandit ac elit. Sed in aliquet enim. Etiam tincidunt tellus sed nulla lobortis, non hendrerit erat gravida.',
	'Cras maximus mi nibh, in condimentum elit laoreet ut. Donec vitae tristique lectus. Proin vel ligula viverra, condimentum orci nec, fringilla nunc. In metus eros, fermentum eu porta sit amet, mattis quis ante. Nulla quam lorem, ornare ut commodo non, sagittis nec magna. Quisque tincidunt, augue non consequat egestas, lectus elit rutrum eros, eu rutrum enim risus ut massa. Suspendisse condimentum elementum ligula, et faucibus dolor tincidunt vel. Fusce placerat massa eget fringilla accumsan. Nulla eleifend posuere leo. Integer diam leo, vulputate sit amet bibendum quis, maximus eget odio. Sed nec posuere metus. Etiam feugiat vel nulla nec ultrices.'
]

export const generateLoremIpsum = (paragraphs = 1): string[] => {
	const loremIpsum = [startLorem]
	for (let i = 1; i < paragraphs; i++) {
		loremIpsum.push(lorem[Math.floor(Math.random() * lorem.length)])
	}
	return loremIpsum
}
